"""Catalogo central do novo sistema de armas v2."""

from __future__ import annotations

from copy import deepcopy


FAMILIAS_ARMA_V2 = {
    "lamina": {
        "nome": "Lamina",
        "categoria": "arma_fisica",
        "tipo_legacy": "Reta",
        "subtipos": ("espada", "sabre", "machado", "martelo"),
        "mecanica": {
            "dano_base": 7.1,
            "peso": 4.3,
            "alcance": 1.7,
            "alcance_minimo": 0.30,
            "arco": 92.0,
            "cadencia": 0.92,
            "startup": 0.14,
            "ativo": 0.09,
            "recovery": 0.22,
            "critico": 0.06,
            "escala_forca": 1.0,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 0.0,
            "spread": 0.0,
            "stagger": 0.55,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 100.0,
        },
        "visual": {
            "silhueta": "corte_limpo",
            "rastro": "lamina_densa",
            "impacto": "faísca_metal",
            "ornamento": "guarda",
            "brilho": 0.20,
        },
    },
    "haste": {
        "nome": "Haste",
        "categoria": "arma_fisica",
        "tipo_legacy": "Reta",
        "subtipos": ("lanca", "alabarda", "cajado"),
        "mecanica": {
            "dano_base": 7.4,
            "peso": 5.1,
            "alcance": 2.15,
            "alcance_minimo": 0.42,
            "arco": 68.0,
            "cadencia": 0.84,
            "startup": 0.16,
            "ativo": 0.08,
            "recovery": 0.25,
            "critico": 0.05,
            "escala_forca": 0.95,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 0.0,
            "spread": 0.0,
            "stagger": 0.62,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 105.0,
        },
        "visual": {
            "silhueta": "estocada_longa",
            "rastro": "agulha",
            "impacto": "estalo",
            "ornamento": "haste",
            "brilho": 0.16,
        },
    },
    "dupla": {
        "nome": "Dupla",
        "categoria": "arma_fisica",
        "tipo_legacy": "Dupla",
        "subtipos": ("adagas", "garras", "tonfas"),
        "mecanica": {
            "dano_base": 5.8,
            "peso": 2.5,
            "alcance": 1.15,
            "alcance_minimo": 0.08,
            "arco": 118.0,
            "cadencia": 1.06,
            "startup": 0.08,
            "ativo": 0.07,
            "recovery": 0.15,
            "critico": 0.11,
            "escala_forca": 0.82,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 2,
            "velocidade_projetil": 0.0,
            "spread": 0.0,
            "stagger": 0.24,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 85.0,
        },
        "visual": {
            "silhueta": "duplo_flash",
            "rastro": "corte_nervoso",
            "impacto": "corte_rasgado",
            "ornamento": "simetria",
            "brilho": 0.28,
        },
    },
    "corrente": {
        "nome": "Corrente",
        "categoria": "arma_fisica",
        "tipo_legacy": "Corrente",
        "subtipos": ("mangual", "kusarigama", "chicote"),
        "mecanica": {
            "dano_base": 7.0,
            "peso": 5.6,
            "alcance": 2.8,
            "alcance_minimo": 0.70,
            "arco": 165.0,
            "cadencia": 0.72,
            "startup": 0.22,
            "ativo": 0.12,
            "recovery": 0.30,
            "critico": 0.05,
            "escala_forca": 0.98,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 0.0,
            "spread": 0.0,
            "stagger": 0.70,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 110.0,
        },
        "visual": {
            "silhueta": "arco_pesado",
            "rastro": "serpenteante",
            "impacto": "choque_esmagador",
            "ornamento": "elo",
            "brilho": 0.24,
        },
    },
    "arremesso": {
        "nome": "Arremesso",
        "categoria": "arma_fisica",
        "tipo_legacy": "Arremesso",
        "subtipos": ("faca", "shuriken", "chakram", "machado"),
        "mecanica": {
            "dano_base": 5.6,
            "peso": 1.7,
            "alcance": 7.8,
            "alcance_minimo": 1.2,
            "arco": 26.0,
            "cadencia": 0.86,
            "startup": 0.15,
            "ativo": 0.05,
            "recovery": 0.24,
            "critico": 0.07,
            "escala_forca": 0.78,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 2,
            "velocidade_projetil": 14.0,
            "spread": 14.0,
            "stagger": 0.22,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 75.0,
        },
        "visual": {
            "silhueta": "vetor_rotativo",
            "rastro": "agulha_luminosa",
            "impacto": "estalo_seco",
            "ornamento": "giro",
            "brilho": 0.18,
        },
    },
    "disparo": {
        "nome": "Disparo",
        "categoria": "arma_fisica",
        "tipo_legacy": "Arco",
        "subtipos": ("arco", "besta", "canhao_leve"),
        "mecanica": {
            "dano_base": 6.2,
            "peso": 3.3,
            "alcance": 10.8,
            "alcance_minimo": 1.8,
            "arco": 18.0,
            "cadencia": 0.72,
            "startup": 0.25,
            "ativo": 0.05,
            "recovery": 0.28,
            "critico": 0.08,
            "escala_forca": 0.74,
            "escala_mana": 0.0,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 32.0,
            "spread": 2.0,
            "stagger": 0.30,
            "qtd_orbitais": 0,
            "forca_disparo": 8.0,
            "durabilidade_base": 90.0,
        },
        "visual": {
            "silhueta": "linha_tensa",
            "rastro": "flecha",
            "impacto": "perfuração",
            "ornamento": "corda",
            "brilho": 0.20,
        },
    },
    "orbital": {
        "nome": "Orbital",
        "categoria": "arma_tatica",
        "tipo_legacy": "Orbital",
        "subtipos": ("escudo", "drone", "laminas", "orbes"),
        "mecanica": {
            "dano_base": 5.7,
            "peso": 4.1,
            "alcance": 1.75,
            "alcance_minimo": 0.0,
            "arco": 360.0,
            "cadencia": 0.78,
            "startup": 0.05,
            "ativo": 0.12,
            "recovery": 0.17,
            "critico": 0.045,
            "escala_forca": 0.62,
            "escala_mana": 0.42,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 14.0,
            "spread": 0.0,
            "stagger": 0.31,
            "qtd_orbitais": 2,
            "forca_disparo": 0.0,
            "durabilidade_base": 120.0,
        },
        "visual": {
            "silhueta": "constelacao_modular",
            "rastro": "orbita_tatica",
            "impacto": "pulso_vetorial",
            "ornamento": "sigilo_guardiao",
            "brilho": 0.38,
        },
    },
    "foco": {
        "nome": "Foco",
        "categoria": "foco_magico",
        "tipo_legacy": "Mágica",
        "subtipos": ("cetro", "grimorio", "orbe", "runas"),
        "mecanica": {
            "dano_base": 6.1,
            "peso": 2.4,
            "alcance": 5.4,
            "alcance_minimo": 0.0,
            "arco": 120.0,
            "cadencia": 0.80,
            "startup": 0.16,
            "ativo": 0.10,
            "recovery": 0.22,
            "critico": 0.06,
            "escala_forca": 0.20,
            "escala_mana": 0.95,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 11.0,
            "spread": 7.0,
            "stagger": 0.34,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 80.0,
        },
        "visual": {
            "silhueta": "sigilo_instavel",
            "rastro": "mana",
            "impacto": "surto_arcano",
            "ornamento": "anel_runico",
            "brilho": 0.55,
        },
    },
    "hibrida": {
        "nome": "Hibrida",
        "categoria": "arma_hibrida",
        "tipo_legacy": "Transformável",
        "subtipos": ("modular", "mutavel", "dupla_forma"),
        "mecanica": {
            "dano_base": 6.7,
            "peso": 4.0,
            "alcance": 2.0,
            "alcance_minimo": 0.2,
            "arco": 102.0,
            "cadencia": 0.90,
            "startup": 0.13,
            "ativo": 0.10,
            "recovery": 0.20,
            "critico": 0.06,
            "escala_forca": 0.84,
            "escala_mana": 0.20,
            "projeteis_por_ataque": 1,
            "velocidade_projetil": 0.0,
            "spread": 0.0,
            "stagger": 0.52,
            "qtd_orbitais": 0,
            "forca_disparo": 0.0,
            "durabilidade_base": 95.0,
        },
        "visual": {
            "silhueta": "dobradiça",
            "rastro": "quebra_ritmo",
            "impacto": "troca_forma",
            "ornamento": "mecanismo",
            "brilho": 0.32,
        },
    },
}


def get_family_spec(familia: str) -> dict:
    return deepcopy(FAMILIAS_ARMA_V2.get(familia, FAMILIAS_ARMA_V2["lamina"]))


def legacy_type_from_family(familia: str) -> str:
    return FAMILIAS_ARMA_V2.get(familia, FAMILIAS_ARMA_V2["lamina"])["tipo_legacy"]
