"""
=============================================================================
NEURAL FIGHTS — Behavior Profiles v1.0
=============================================================================
Define COMO cada personalidade realmente se comporta no combate.
Substitui os ±0.1 genéricos por perfis concretos e mensuráveis.

Cada perfil define:
  - Thresholds (quando recuar, quando atacar)
  - Multiplicadores (bloqueio, esquiva, combo)
  - Reações emocionais (o que acontece ao tomar dano)
  - Regras exclusivas (perseguir sempre, nunca fugir, etc.)

SEGURANÇA: Se o perfil não existir, FALLBACK_PROFILE é usado (neutro).
=============================================================================
"""

# ─── Reações possíveis ao tomar dano ────────────────────────────────────────
# "RAIVA"   → aumenta agressividade e raiva
# "RECUAR"  → tenta criar distância
# "MEDO"    → aumenta medo, pode fugir
# "NADA"    → não reage emocionalmente
# "FURIA"   → raiva extrema, ignora defesa
# "FOCO"    → fica mais concentrado e preciso
# "ADAPTAR" → muda de estratégia

FALLBACK_PROFILE = {
    "recuar_threshold": 0.30,
    "ataque_min_chance": 0.5,
    "ataque_bonus_chance": 0.0,
    "perseguir_sempre": False,
    "nunca_recua": False,
    "dano_recebido_reacao": "NADA",
    "bloqueio_mult": 1.0,
    "esquiva_mult": 1.0,
    "combo_tendencia": 1.0,
    "skill_agressividade": 1.0,
    "risco_tolerancia": 0.5,
    "raiva_ganho_mult": 1.0,
    "medo_ganho_mult": 1.0,
    "pressao_mult": 1.0,
    "paciencia_mult": 1.0,
    "execute_threshold": 0.25,
    "approach_weight": 1.0,
    "retreat_weight": 1.0,
    "flank_weight": 1.0,
    "poke_weight": 1.0,
}

BEHAVIOR_PROFILES = {
    # ═══════════════════════════════════════════════════════════════════════════
    # AGRESSIVOS
    # ═══════════════════════════════════════════════════════════════════════════
    "Agressivo": {
        "recuar_threshold": 0.12,
        "ataque_min_chance": 0.75,
        "ataque_bonus_chance": 0.20,
        "perseguir_sempre": True,
        "nunca_recua": False,
        "dano_recebido_reacao": "RAIVA",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 0.4,
        "combo_tendencia": 1.6,
        "skill_agressividade": 1.4,
        "risco_tolerancia": 0.8,
        "raiva_ganho_mult": 1.5,
        "medo_ganho_mult": 0.3,
        "pressao_mult": 1.8,
        "paciencia_mult": 0.3,
        "execute_threshold": 0.35,
        "approach_weight": 1.8,
        "retreat_weight": 0.3,
        "flank_weight": 0.7,
        "poke_weight": 0.5,
    },
    "Berserker": {
        "recuar_threshold": 0.05,
        "ataque_min_chance": 0.85,
        "ataque_bonus_chance": 0.30,
        "perseguir_sempre": True,
        "nunca_recua": True,
        "dano_recebido_reacao": "FURIA",
        "bloqueio_mult": 0.1,
        "esquiva_mult": 0.2,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.6,
        "risco_tolerancia": 0.95,
        "raiva_ganho_mult": 2.5,
        "medo_ganho_mult": 0.1,
        "pressao_mult": 2.0,
        "paciencia_mult": 0.1,
        "execute_threshold": 0.40,
        "approach_weight": 2.0,
        "retreat_weight": 0.1,
        "flank_weight": 0.4,
        "poke_weight": 0.2,
    },
    "Perseguidor": {
        "recuar_threshold": 0.10,
        "ataque_min_chance": 0.70,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": True,
        "nunca_recua": False,
        "dano_recebido_reacao": "RAIVA",
        "bloqueio_mult": 0.5,
        "esquiva_mult": 0.6,
        "combo_tendencia": 1.3,
        "skill_agressividade": 1.2,
        "risco_tolerancia": 0.7,
        "raiva_ganho_mult": 1.3,
        "medo_ganho_mult": 0.4,
        "pressao_mult": 2.2,
        "paciencia_mult": 0.4,
        "execute_threshold": 0.40,
        "approach_weight": 2.5,
        "retreat_weight": 0.2,
        "flank_weight": 1.0,
        "poke_weight": 0.3,
    },
    "Destruidor": {
        "recuar_threshold": 0.08,
        "ataque_min_chance": 0.80,
        "ataque_bonus_chance": 0.25,
        "perseguir_sempre": True,
        "nunca_recua": True,
        "dano_recebido_reacao": "FURIA",
        "bloqueio_mult": 0.2,
        "esquiva_mult": 0.2,
        "combo_tendencia": 1.8,
        "skill_agressividade": 1.5,
        "risco_tolerancia": 0.9,
        "raiva_ganho_mult": 2.0,
        "medo_ganho_mult": 0.2,
        "pressao_mult": 2.0,
        "paciencia_mult": 0.2,
        "execute_threshold": 0.35,
        "approach_weight": 2.0,
        "retreat_weight": 0.1,
        "flank_weight": 0.5,
        "poke_weight": 0.3,
    },
    "Viking": {
        "recuar_threshold": 0.08,
        "ataque_min_chance": 0.80,
        "ataque_bonus_chance": 0.20,
        "perseguir_sempre": True,
        "nunca_recua": True,
        "dano_recebido_reacao": "FURIA",
        "bloqueio_mult": 0.2,
        "esquiva_mult": 0.3,
        "combo_tendencia": 1.7,
        "skill_agressividade": 1.5,
        "risco_tolerancia": 0.95,
        "raiva_ganho_mult": 2.0,
        "medo_ganho_mult": 0.05,
        "pressao_mult": 1.8,
        "paciencia_mult": 0.2,
        "execute_threshold": 0.35,
        "approach_weight": 2.0,
        "retreat_weight": 0.1,
        "flank_weight": 0.8,
        "poke_weight": 0.3,
    },
    "Zerg Rush": {
        "recuar_threshold": 0.05,
        "ataque_min_chance": 0.85,
        "ataque_bonus_chance": 0.25,
        "perseguir_sempre": True,
        "nunca_recua": True,
        "dano_recebido_reacao": "NADA",
        "bloqueio_mult": 0.1,
        "esquiva_mult": 0.2,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.8,
        "risco_tolerancia": 0.9,
        "raiva_ganho_mult": 1.0,
        "medo_ganho_mult": 0.1,
        "pressao_mult": 2.5,
        "paciencia_mult": 0.05,
        "execute_threshold": 0.40,
        "approach_weight": 2.5,
        "retreat_weight": 0.05,
        "flank_weight": 0.3,
        "poke_weight": 0.2,
    },
    "Pugilista": {
        "recuar_threshold": 0.15,
        "ataque_min_chance": 0.75,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": True,
        "nunca_recua": False,
        "dano_recebido_reacao": "RAIVA",
        "bloqueio_mult": 1.2,
        "esquiva_mult": 1.3,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.7,
        "raiva_ganho_mult": 1.3,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 1.5,
        "paciencia_mult": 0.5,
        "execute_threshold": 0.30,
        "approach_weight": 1.5,
        "retreat_weight": 0.4,
        "flank_weight": 0.6,
        "poke_weight": 0.3,
    },
    "Predador Alfa": {
        "recuar_threshold": 0.10,
        "ataque_min_chance": 0.75,
        "ataque_bonus_chance": 0.20,
        "perseguir_sempre": True,
        "nunca_recua": False,
        "dano_recebido_reacao": "FOCO",
        "bloqueio_mult": 0.4,
        "esquiva_mult": 0.6,
        "combo_tendencia": 1.5,
        "skill_agressividade": 1.3,
        "risco_tolerancia": 0.8,
        "raiva_ganho_mult": 1.2,
        "medo_ganho_mult": 0.2,
        "pressao_mult": 2.0,
        "paciencia_mult": 0.6,
        "execute_threshold": 0.45,
        "approach_weight": 2.0,
        "retreat_weight": 0.2,
        "flank_weight": 1.2,
        "poke_weight": 0.5,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # DEFENSIVOS
    # ═══════════════════════════════════════════════════════════════════════════
    "Defensivo": {
        "recuar_threshold": 0.50,
        "ataque_min_chance": 0.30,
        "ataque_bonus_chance": 0.0,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "RECUAR",
        "bloqueio_mult": 2.0,
        "esquiva_mult": 1.5,
        "combo_tendencia": 0.5,
        "skill_agressividade": 0.6,
        "risco_tolerancia": 0.2,
        "raiva_ganho_mult": 0.5,
        "medo_ganho_mult": 1.5,
        "pressao_mult": 0.3,
        "paciencia_mult": 2.0,
        "execute_threshold": 0.20,
        "approach_weight": 0.5,
        "retreat_weight": 2.0,
        "flank_weight": 0.8,
        "poke_weight": 1.5,
    },
    "Protetor": {
        "recuar_threshold": 0.40,
        "ataque_min_chance": 0.40,
        "ataque_bonus_chance": 0.05,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "NADA",
        "bloqueio_mult": 2.5,
        "esquiva_mult": 1.0,
        "combo_tendencia": 0.6,
        "skill_agressividade": 0.7,
        "risco_tolerancia": 0.2,
        "raiva_ganho_mult": 0.3,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 0.4,
        "paciencia_mult": 2.0,
        "execute_threshold": 0.20,
        "approach_weight": 0.6,
        "retreat_weight": 1.5,
        "flank_weight": 0.5,
        "poke_weight": 1.0,
    },
    "Fantasma": {
        "recuar_threshold": 0.45,
        "ataque_min_chance": 0.35,
        "ataque_bonus_chance": 0.05,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "RECUAR",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 2.5,
        "combo_tendencia": 0.7,
        "skill_agressividade": 0.8,
        "risco_tolerancia": 0.3,
        "raiva_ganho_mult": 0.3,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 0.4,
        "paciencia_mult": 1.5,
        "execute_threshold": 0.25,
        "approach_weight": 0.5,
        "retreat_weight": 2.0,
        "flank_weight": 1.5,
        "poke_weight": 2.0,
    },
    "Masoquista": {
        "recuar_threshold": 0.08,
        "ataque_min_chance": 0.55,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "FURIA",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 0.3,
        "combo_tendencia": 1.2,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.9,
        "raiva_ganho_mult": 2.0,
        "medo_ganho_mult": 0.1,
        "pressao_mult": 0.5,
        "paciencia_mult": 1.5,
        "execute_threshold": 0.25,
        "approach_weight": 1.0,
        "retreat_weight": 0.3,
        "flank_weight": 0.5,
        "poke_weight": 0.5,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # TÁTICOS / CALCULISTAS
    # ═══════════════════════════════════════════════════════════════════════════
    "Tático": {
        "recuar_threshold": 0.30,
        "ataque_min_chance": 0.50,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 1.3,
        "esquiva_mult": 1.3,
        "combo_tendencia": 1.2,
        "skill_agressividade": 1.2,
        "risco_tolerancia": 0.4,
        "raiva_ganho_mult": 0.5,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 1.0,
        "paciencia_mult": 1.5,
        "execute_threshold": 0.25,
        "approach_weight": 1.0,
        "retreat_weight": 1.0,
        "flank_weight": 1.5,
        "poke_weight": 1.5,
    },
    "Samurai": {
        "recuar_threshold": 0.20,
        "ataque_min_chance": 0.55,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "FOCO",
        "bloqueio_mult": 1.5,
        "esquiva_mult": 1.0,
        "combo_tendencia": 0.8,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.5,
        "raiva_ganho_mult": 0.3,
        "medo_ganho_mult": 0.2,
        "pressao_mult": 0.8,
        "paciencia_mult": 2.5,
        "execute_threshold": 0.20,
        "approach_weight": 0.8,
        "retreat_weight": 0.8,
        "flank_weight": 0.5,
        "poke_weight": 0.8,
    },
    "Contemplativo": {
        "recuar_threshold": 0.35,
        "ataque_min_chance": 0.40,
        "ataque_bonus_chance": 0.05,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 1.5,
        "esquiva_mult": 1.5,
        "combo_tendencia": 1.0,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.3,
        "raiva_ganho_mult": 0.2,
        "medo_ganho_mult": 0.3,
        "pressao_mult": 0.5,
        "paciencia_mult": 3.0,
        "execute_threshold": 0.20,
        "approach_weight": 0.7,
        "retreat_weight": 1.2,
        "flank_weight": 1.3,
        "poke_weight": 1.8,
    },
    "Psicopata": {
        "recuar_threshold": 0.15,
        "ataque_min_chance": 0.65,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": True,
        "nunca_recua": False,
        "dano_recebido_reacao": "NADA",
        "bloqueio_mult": 0.5,
        "esquiva_mult": 0.8,
        "combo_tendencia": 1.3,
        "skill_agressividade": 1.3,
        "risco_tolerancia": 0.7,
        "raiva_ganho_mult": 0.0,
        "medo_ganho_mult": 0.0,
        "pressao_mult": 1.5,
        "paciencia_mult": 1.5,
        "execute_threshold": 0.35,
        "approach_weight": 1.5,
        "retreat_weight": 0.5,
        "flank_weight": 1.2,
        "poke_weight": 1.0,
    },
    "Sombrio": {
        "recuar_threshold": 0.25,
        "ataque_min_chance": 0.50,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "RECUAR",
        "bloqueio_mult": 0.8,
        "esquiva_mult": 1.5,
        "combo_tendencia": 1.0,
        "skill_agressividade": 1.2,
        "risco_tolerancia": 0.4,
        "raiva_ganho_mult": 0.5,
        "medo_ganho_mult": 0.3,
        "pressao_mult": 0.8,
        "paciencia_mult": 2.5,
        "execute_threshold": 0.30,
        "approach_weight": 0.6,
        "retreat_weight": 1.2,
        "flank_weight": 2.0,
        "poke_weight": 1.5,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # MOBILE / ACROBÁTICOS
    # ═══════════════════════════════════════════════════════════════════════════
    "Assassino": {
        "recuar_threshold": 0.25,
        "ataque_min_chance": 0.60,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "RECUAR",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 2.0,
        "combo_tendencia": 1.5,
        "skill_agressividade": 1.3,
        "risco_tolerancia": 0.6,
        "raiva_ganho_mult": 0.7,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 0.8,
        "paciencia_mult": 1.2,
        "execute_threshold": 0.35,
        "approach_weight": 1.2,
        "retreat_weight": 1.2,
        "flank_weight": 2.5,
        "poke_weight": 1.0,
    },
    "Acrobático": {
        "recuar_threshold": 0.30,
        "ataque_min_chance": 0.55,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 2.5,
        "combo_tendencia": 1.2,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.6,
        "raiva_ganho_mult": 0.7,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 0.8,
        "paciencia_mult": 0.8,
        "execute_threshold": 0.25,
        "approach_weight": 1.0,
        "retreat_weight": 1.0,
        "flank_weight": 2.0,
        "poke_weight": 1.0,
    },
    "Capoeirista": {
        "recuar_threshold": 0.25,
        "ataque_min_chance": 0.60,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 0.3,
        "esquiva_mult": 2.2,
        "combo_tendencia": 1.5,
        "skill_agressividade": 0.9,
        "risco_tolerancia": 0.65,
        "raiva_ganho_mult": 0.8,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 1.0,
        "paciencia_mult": 0.7,
        "execute_threshold": 0.25,
        "approach_weight": 1.2,
        "retreat_weight": 0.8,
        "flank_weight": 1.8,
        "poke_weight": 0.8,
    },

    # ═══════════════════════════════════════════════════════════════════════════
    # ESPECIAIS / MISTOS
    # ═══════════════════════════════════════════════════════════════════════════
    "Showman": {
        "recuar_threshold": 0.20,
        "ataque_min_chance": 0.60,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "RAIVA",
        "bloqueio_mult": 0.7,
        "esquiva_mult": 1.2,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.5,
        "risco_tolerancia": 0.7,
        "raiva_ganho_mult": 1.0,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 1.2,
        "paciencia_mult": 0.6,
        "execute_threshold": 0.30,
        "approach_weight": 1.2,
        "retreat_weight": 0.6,
        "flank_weight": 1.5,
        "poke_weight": 0.8,
    },
    "Equilibrado": {
        "recuar_threshold": 0.30,
        "ataque_min_chance": 0.50,
        "ataque_bonus_chance": 0.05,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 1.0,
        "esquiva_mult": 1.0,
        "combo_tendencia": 1.0,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.5,
        "raiva_ganho_mult": 1.0,
        "medo_ganho_mult": 1.0,
        "pressao_mult": 1.0,
        "paciencia_mult": 1.0,
        "execute_threshold": 0.25,
        "approach_weight": 1.0,
        "retreat_weight": 1.0,
        "flank_weight": 1.0,
        "poke_weight": 1.0,
    },
    "Tempestade": {
        "recuar_threshold": 0.25,
        "ataque_min_chance": 0.50,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "FURIA",
        "bloqueio_mult": 0.8,
        "esquiva_mult": 0.8,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.8,
        "risco_tolerancia": 0.6,
        "raiva_ganho_mult": 2.0,
        "medo_ganho_mult": 0.3,
        "pressao_mult": 0.5,
        "paciencia_mult": 2.0,
        "execute_threshold": 0.30,
        "approach_weight": 0.8,
        "retreat_weight": 0.8,
        "flank_weight": 1.0,
        "poke_weight": 1.2,
    },
    "Caótico": {
        "recuar_threshold": 0.20,
        "ataque_min_chance": 0.55,
        "ataque_bonus_chance": 0.15,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "ADAPTAR",
        "bloqueio_mult": 0.7,
        "esquiva_mult": 1.0,
        "combo_tendencia": 1.5,
        "skill_agressividade": 1.5,
        "risco_tolerancia": 0.8,
        "raiva_ganho_mult": 1.5,
        "medo_ganho_mult": 0.5,
        "pressao_mult": 1.2,
        "paciencia_mult": 0.4,
        "execute_threshold": 0.30,
        "approach_weight": 1.3,
        "retreat_weight": 0.7,
        "flank_weight": 1.5,
        "poke_weight": 1.0,
    },
    "Artista Marcial": {
        "recuar_threshold": 0.25,
        "ataque_min_chance": 0.55,
        "ataque_bonus_chance": 0.10,
        "perseguir_sempre": False,
        "nunca_recua": False,
        "dano_recebido_reacao": "FOCO",
        "bloqueio_mult": 1.0,
        "esquiva_mult": 1.8,
        "combo_tendencia": 2.0,
        "skill_agressividade": 1.0,
        "risco_tolerancia": 0.5,
        "raiva_ganho_mult": 0.5,
        "medo_ganho_mult": 0.3,
        "pressao_mult": 0.8,
        "paciencia_mult": 1.5,
        "execute_threshold": 0.25,
        "approach_weight": 1.0,
        "retreat_weight": 0.8,
        "flank_weight": 1.5,
        "poke_weight": 1.2,
    },
}


# ─── TRAIT EFFECTS TABLE ───────────────────────────────────────────────────
# Maps each trait to concrete vote weight modifications.
# Format: {action_name: weight_to_add}
# Applied in _estrategia_generica section 2/4.
# Only traits that should meaningfully change behavior are listed.

TRAIT_EFFECTS = {
    # ═══ AGRESSIVIDADE ═══
    "IMPRUDENTE":        {"MATAR": 0.8, "ESMAGAR": 0.6, "RECUAR": -0.5, "FUGIR": -0.8, "BLOQUEAR": -0.5},
    "AGRESSIVO":         {"MATAR": 0.6, "APROXIMAR": 0.5, "PRESSIONAR": 0.5, "RECUAR": -0.3},
    "BERSERKER":         {"MATAR": 0.8, "ESMAGAR": 0.5, "RECUAR": -0.6, "FUGIR": -0.8},
    "OPORTUNISTA":       {"CONTRA_ATAQUE": 0.5, "PRESSIONAR": 0.3, "FLANQUEAR": 0.3},
    "SANGUINARIO":       {"MATAR": 0.7, "ESMAGAR": 0.4, "RECUAR": -0.3},
    "PREDADOR":          {"APROXIMAR": 0.6, "PRESSIONAR": 0.5, "FLANQUEAR": 0.4},
    "SELVAGEM":          {"MATAR": 0.5, "ESMAGAR": 0.4, "ATAQUE_RAPIDO": 0.4},
    "IMPLACAVEL":        {"MATAR": 0.5, "PRESSIONAR": 0.5, "RECUAR": -0.5, "FUGIR": -1.0},
    "FURIOSO":           {"MATAR": 0.5, "ESMAGAR": 0.3, "RECUAR": -0.2},
    "BRUTAL":            {"ESMAGAR": 0.7, "MATAR": 0.4},
    "PRESSAO_CONSTANTE": {"PRESSIONAR": 0.8, "APROXIMAR": 0.5, "RECUAR": -0.4},
    "FINALIZADOR_NATO":  {"MATAR": 0.4},  # Bônus dinâmico quando inimigo com HP baixo
    "ENCURRALADOR":      {"PRESSIONAR": 0.6, "FLANQUEAR": 0.5},
    "DOMINADOR":         {"PRESSIONAR": 0.7, "MATAR": 0.4, "RECUAR": -0.3},
    "CARRASCO":          {"MATAR": 0.3, "PRESSIONAR": 0.5},
    "DESTRUIDOR":        {"ESMAGAR": 0.8, "MATAR": 0.6, "RECUAR": -0.4},
    "INCANSAVEL":        {"PRESSIONAR": 0.6, "APROXIMAR": 0.4, "RECUAR": -0.3},
    "EXPLOSIVO":         {"MATAR": 0.6, "ESMAGAR": 0.5},
    "ALPHA":             {"PRESSIONAR": 0.7, "MATAR": 0.5, "RECUAR": -0.5},
    "SEDENTO":           {"MATAR": 0.5, "APROXIMAR": 0.5, "RECUAR": -0.3},
    "PROVOCADOR":        {"PRESSIONAR": 0.5, "CIRCULAR": 0.3},
    "TOURO":             {"APROXIMAR": 0.8, "MATAR": 0.5, "FLANQUEAR": -0.3},
    "MARTELO":           {"ESMAGAR": 0.8, "MATAR": 0.3},
    "TRITURADOR":        {"ESMAGAR": 0.7, "MATAR": 0.5, "PRESSIONAR": 0.3},
    "DEVORADOR":         {"MATAR": 0.5, "PRESSIONAR": 0.5, "APROXIMAR": 0.3},

    # ═══ DEFENSIVO ═══
    "COVARDE":           {"FUGIR": 0.8, "RECUAR": 0.6, "MATAR": -0.3, "APROXIMAR": -0.3},
    "CAUTELOSO":         {"COMBATE": 0.4, "CIRCULAR": 0.3, "RECUAR": 0.3, "MATAR": -0.2},
    "PACIENTE":          {"COMBATE": 0.5, "CONTRA_ATAQUE": 0.4, "MATAR": -0.2},
    "REATIVO":           {"CONTRA_ATAQUE": 0.7, "COMBATE": 0.3},
    "TANQUE":            {"BLOQUEAR": 0.5, "COMBATE": 0.3, "RECUAR": -0.3},
    "PROTETOR":          {"BLOQUEAR": 0.6, "COMBATE": 0.3, "RECUAR": -0.2},
    "EVASIVO":           {"CIRCULAR": 0.5, "FLANQUEAR": 0.4, "RECUAR": 0.3},
    "PARANOICO":         {"RECUAR": 0.4, "CIRCULAR": 0.3, "BLOQUEAR": 0.3},
    "MEDROSO":           {"FUGIR": 0.6, "RECUAR": 0.5, "MATAR": -0.4},
    "PRUDENTE":          {"COMBATE": 0.4, "CIRCULAR": 0.3, "MATAR": -0.1},
    "LEITURA_PERFEITA":  {"CONTRA_ATAQUE": 0.6, "COMBATE": 0.3},
    "TIMING_PRECISO":    {"CONTRA_ATAQUE": 0.7},
    "COBERTURA_MESTRE":  {"CIRCULAR": 0.4, "BLOQUEAR": 0.3},
    "BLINDADO":          {"BLOQUEAR": 0.3, "RECUAR": -0.2},
    "INABALAVEL":        {"COMBATE": 0.4, "RECUAR": -0.3, "FUGIR": -0.3},
    "MURALHA":           {"BLOQUEAR": 0.6, "RECUAR": -0.5, "FUGIR": -0.5},
    "TARTARUGA":         {"BLOQUEAR": 0.8, "RECUAR": 0.3, "MATAR": -0.3},
    "ABSORVEDOR":        {"CONTRA_ATAQUE": 0.5, "BLOQUEAR": 0.3},
    "PREVISOR":          {"CONTRA_ATAQUE": 0.5, "CIRCULAR": 0.3},
    "FANTASMA":          {"CIRCULAR": 0.5, "RECUAR": 0.4, "FLANQUEAR": 0.3},
    "RESILIENTE":        {"COMBATE": 0.3, "RECUAR": -0.2},
    "ESPELHO":           {"CONTRA_ATAQUE": 0.6, "COMBATE": 0.3},
    "SENTINEL":          {"BLOQUEAR": 0.5, "COMBATE": 0.4, "RECUAR": -0.3},
    "ARMADILHEIRO":      {"CIRCULAR": 0.4, "POKE": 0.3},
    "SOBREVIVENTE":      {"RECUAR": 0.4, "FUGIR": 0.3, "CIRCULAR": 0.3},

    # ═══ MOBILIDADE ═══
    "SALTADOR":          {"CIRCULAR": 0.3, "FLANQUEAR": 0.3},
    "ACROBATA":          {"FLANQUEAR": 0.5, "CIRCULAR": 0.4},
    "ERRATICO":          {"FLANQUEAR": 0.3, "CIRCULAR": 0.3, "ATAQUE_RAPIDO": 0.2},
    "FLANQUEADOR":       {"FLANQUEAR": 0.8, "CIRCULAR": 0.3},
    "PERSEGUIDOR":       {"APROXIMAR": 0.7, "PRESSIONAR": 0.4, "RECUAR": -0.3},
    "VELOZ":             {"FLANQUEAR": 0.4, "ATAQUE_RAPIDO": 0.5, "CIRCULAR": 0.3},
    "ESTATICO":          {"COMBATE": 0.5, "BLOQUEAR": 0.3, "FLANQUEAR": -0.3},
    "DESLIZANTE":        {"CIRCULAR": 0.4, "FLANQUEAR": 0.3},
    "CAOTICO":           {"FLANQUEAR": 0.3, "CIRCULAR": 0.3, "ATAQUE_RAPIDO": 0.2, "MATAR": 0.2},
    "ESPACAMENTO_MESTRE": {"COMBATE": 0.5, "CIRCULAR": 0.4, "POKE": 0.4},
    "MICRO_AJUSTES":     {"COMBATE": 0.4, "CIRCULAR": 0.3},
    "NAVEGADOR":         {"FLANQUEAR": 0.4, "CIRCULAR": 0.3},
    "ARENA_MASTER":      {"FLANQUEAR": 0.4, "CIRCULAR": 0.3, "PRESSIONAR": 0.2},
    "DANÇARINO":         {"CIRCULAR": 0.5, "FLANQUEAR": 0.4},
    "RELAMPAGO":         {"ATAQUE_RAPIDO": 0.6, "APROXIMAR": 0.4},
    "BORBOLETA":         {"CIRCULAR": 0.5, "FLANQUEAR": 0.4, "RECUAR": 0.2},
    "SERPENTE":           {"FLANQUEAR": 0.5, "CIRCULAR": 0.4},
    "TELEPORTER":        {"FLANQUEAR": 0.5, "ATAQUE_RAPIDO": 0.4},
    "ORBITA":            {"CIRCULAR": 0.7, "FLANQUEAR": 0.3},
    "ZIGZAG":            {"CIRCULAR": 0.4, "FLANQUEAR": 0.4},
    "PIVOTADOR":         {"CIRCULAR": 0.5, "CONTRA_ATAQUE": 0.3},
    "RASTREADOR":        {"APROXIMAR": 0.5, "PRESSIONAR": 0.4},
    "KITER":             {"RECUAR": 0.3, "POKE": 0.6, "CIRCULAR": 0.3},
    "COLADO":            {"APROXIMAR": 0.7, "PRESSIONAR": 0.5, "RECUAR": -0.4},
    "IOIO":              {"APROXIMAR": 0.3, "RECUAR": 0.3, "ATAQUE_RAPIDO": 0.3},

    # ═══ SKILLS ═══
    "SPAMMER":           {"POKE": 0.3},
    "CALCULISTA":        {"FLANQUEAR": 0.3, "COMBATE": 0.3},
    "CONSERVADOR":       {},  # Afeta skills, não ações
    "EXPLOSIVO_SKILLS":  {"MATAR": 0.2},
    "COMBO_MASTER":      {"MATAR": 0.3, "PRESSIONAR": 0.2},
    "SNIPER":            {"POKE": 0.5, "RECUAR": 0.2},
    "CLOSE_RANGE":       {"APROXIMAR": 0.4, "MATAR": 0.3},
    "AREA_DENIAL":       {"CIRCULAR": 0.3, "POKE": 0.3},
    "DEBUFFER":          {"POKE": 0.3, "CIRCULAR": 0.2},
    "SUPPORT":           {"COMBATE": 0.3, "CIRCULAR": 0.2},
    "SETUP_ARTIST":      {"CIRCULAR": 0.3, "POKE": 0.3},
    "ZONE_CONTROLLER":   {"CIRCULAR": 0.4, "POKE": 0.3},
    "TECNICO":           {"COMBATE": 0.3, "FLANQUEAR": 0.2},
    "DESPERDICADOR":     {"MATAR": 0.2, "POKE": 0.2},
    "CANALIZADOR":       {"COMBATE": 0.3},
    "INSTANT_CAST":      {"ATAQUE_RAPIDO": 0.3, "MATAR": 0.2},
    "CHAIN_CASTER":      {"PRESSIONAR": 0.3, "MATAR": 0.2},
    "FINISHER":          {"MATAR": 0.3},  # Bônus dinâmico em HP baixo
    "OPENER":            {"PRESSIONAR": 0.3, "APROXIMAR": 0.2},
    "MANA_BURNER":       {"MATAR": 0.2},
    "COOLDOWN_WATCHER":  {"CONTRA_ATAQUE": 0.3, "PRESSIONAR": 0.2},
    "SKILL_BAITER":      {"CIRCULAR": 0.3, "RECUAR": 0.2},
    "CANCELADOR":        {"CONTRA_ATAQUE": 0.3},
    "ZONER":             {"CIRCULAR": 0.4, "POKE": 0.4},

    # ═══ MENTAL ═══
    "VINGATIVO":         {"MATAR": 0.3},  # Bônus dinâmico com raiva
    "DETERMINADO":       {"MATAR": 0.2, "PRESSIONAR": 0.2, "FUGIR": -0.3},
    "ADAPTAVEL":         {},  # Efeito dinâmico: muda estratégia
    "FRIO":              {},  # Efeito: emoções não afetam decisões
    "EMOTIVO":           {},  # Efeito: emoções afetam 2x mais
    "FOCADO":            {"COMBATE": 0.3},
    "DISPERSO":          {},  # Efeito dinâmico: alterna alvos
    "TEIMOSO":           {"MATAR": 0.3, "PRESSIONAR": 0.2},
    "CRIATIVO":          {"FLANQUEAR": 0.3, "CIRCULAR": 0.2, "ATAQUE_RAPIDO": 0.2},
    "METODICO":          {"COMBATE": 0.4, "PRESSIONAR": 0.3},
    "CLUTCH_PLAYER":     {},  # Bônus dinâmico: melhor com HP baixo
    "TILTER":            {},  # Efeito dinâmico: pior com HP baixo
    "AWARENESS_ALTO":    {"CONTRA_ATAQUE": 0.3, "CIRCULAR": 0.2},
    "PSICOPATA":         {"MATAR": 0.3, "PRESSIONAR": 0.3, "FUGIR": -0.5},
    "ANALITICO":         {"COMBATE": 0.3, "FLANQUEAR": 0.3, "CONTRA_ATAQUE": 0.2},
    "INSTINTIVO":        {"ATAQUE_RAPIDO": 0.4, "MATAR": 0.3},
    "CEREBRAL":          {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.3},
    "IMPULSIVO":         {"MATAR": 0.5, "ATAQUE_RAPIDO": 0.3, "RECUAR": -0.2},
    "RESILIENTE_MENTAL": {"COMBATE": 0.2, "FUGIR": -0.2},
    "TRAUMATIZADO":      {"RECUAR": 0.3, "FUGIR": 0.2},
    "CONFIANTE":         {"MATAR": 0.3, "PRESSIONAR": 0.3, "RECUAR": -0.2},
    "INSEGURO":          {"RECUAR": 0.3, "COMBATE": 0.2, "MATAR": -0.2},
    "ZEN":               {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.3},
    "CAOS_MENTAL":       {"MATAR": 0.2, "CIRCULAR": 0.2, "RECUAR": 0.2, "FLANQUEAR": 0.2},
    "PREDITOR":          {"CONTRA_ATAQUE": 0.5, "FLANQUEAR": 0.3},
    "REATIVO_MENTAL":    {"CONTRA_ATAQUE": 0.5, "COMBATE": 0.3},
    "OBSESSIVO":         {"PRESSIONAR": 0.5, "APROXIMAR": 0.3},

    # ═══ ESPECIAIS ═══
    "SHOWMAN":           {"MATAR": 0.2, "FLANQUEAR": 0.3},
    "ASSASSINO_NATO":    {"MATAR": 0.5, "FLANQUEAR": 0.4},
    "BERSERKER_RAGE":    {},  # Efeito dinâmico: modo fúria em HP crítico
    "PHOENIX":           {},  # Efeito dinâmico: mais forte perto da morte
    "VAMPIRO":           {"MATAR": 0.3, "PRESSIONAR": 0.3},
    "KAMIKAZE":          {"MATAR": 1.0, "ESMAGAR": 0.8, "RECUAR": -1.0, "FUGIR": -1.0},
    "TRICKSTER":         {"FLANQUEAR": 0.5, "CIRCULAR": 0.4},
    "HONORAVEL":         {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.3, "FUGIR": -0.5},
    "COVARDE_TATICO":    {"RECUAR": 0.4, "POKE": 0.5, "CIRCULAR": 0.3},
    "ULTIMO_SUSPIRO":    {},  # Efeito dinâmico: burst com HP < 10%
    "MOMENTUM_RIDER":    {},  # Efeito dinâmico: melhor ganhando
    "UNDERDOG":          {},  # Efeito dinâmico: melhor perdendo
    "BAITER_NATO":       {"CIRCULAR": 0.4, "CONTRA_ATAQUE": 0.5},
    "WALL_FIGHTER":      {"PRESSIONAR": 0.3, "COMBATE": 0.3},
    "PILLAR_DANCER":     {"CIRCULAR": 0.5, "FLANQUEAR": 0.3},
    "METAMORFO":         {},  # Efeito dinâmico: muda estilo durante a luta
    "DUPLA_PERSONALIDADE": {},  # Efeito dinâmico: alterna personalidades
    "GLUTTON":           {"MATAR": 0.3, "PRESSIONAR": 0.3, "APROXIMAR": 0.3},
    "PERFECCIONISTA":    {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.3},
    "STYLIST":           {"FLANQUEAR": 0.4, "CIRCULAR": 0.3},
    "EFICIENTE":         {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.3},
    "CAÇADOR_GLORIA":    {"MATAR": 0.4, "ESMAGAR": 0.3},
    "MINIMALISTA":       {"COMBATE": 0.3, "POKE": 0.3},
    "MAXIMALISTA":       {"MATAR": 0.5, "PRESSIONAR": 0.4, "ESMAGAR": 0.3},
    "SÁDICO":            {"PRESSIONAR": 0.5, "MATAR": 0.3},
    "MASOQUISTA":        {},  # Efeito dinâmico: mais forte com dano recebido
    "APOSTADOR":         {"MATAR": 0.4, "ESMAGAR": 0.3},
    "SEGURO":            {"COMBATE": 0.4, "CIRCULAR": 0.3, "MATAR": -0.2},
    "LENDARIO":          {"MATAR": 0.3, "FLANQUEAR": 0.3},
    "PRÁTICO":           {"MATAR": 0.3, "COMBATE": 0.3},
    "ARTISTA_MARCIAL":   {"COMBATE": 0.4, "FLANQUEAR": 0.3, "CIRCULAR": 0.3},
    "GLADIADOR":         {"MATAR": 0.3, "PRESSIONAR": 0.3},
    "SAMURAI":           {"COMBATE": 0.4, "CONTRA_ATAQUE": 0.5, "FUGIR": -0.5},
    "VIKING":            {"MATAR": 0.5, "ESMAGAR": 0.4, "RECUAR": -0.5, "FUGIR": -0.8},
    "NINJA_MENTAL":      {"FLANQUEAR": 0.5, "CIRCULAR": 0.3},
}


def get_behavior_profile(personality_name: str) -> dict:
    """Returns the behavior profile for a personality, with safe fallback."""
    return BEHAVIOR_PROFILES.get(personality_name, FALLBACK_PROFILE)


def get_trait_effects(trait_name: str) -> dict:
    """Returns vote weight modifications for a trait. Empty dict if unknown."""
    return TRAIT_EFFECTS.get(trait_name, {})
